### ISSUE TITLE
Unable to access dropbox files.

### ISSUE THREAD

**Issue by awws** [arc42/arc42-template#61]
Hello,

I am unable to access the landing zone (http://confluence.arc42.org/display/LANDINGZON/landing+zone) download links for confluence material (https://dl.dropboxusercontent.com/u/45486/arc42-downloads/confluence/templateEN-V6-confluence-53.xml.zip). Would you make it available please.

Kind regards

Alex

**Comment by gernotstarke** [comment]
you got a typo in the URL:

http://confluence.arc42.org/display/LANDINGZON/landing+zone
is alive and kicking...


(same for the dropbox-download-site)

might try the direct dropbox download:

https://www.dropbox.com/s/yvlkkozpt36rovr/templateEN-V6-confluence-53.xml.zip?dl=0 <https://www.dropbox.com/s/yvlkkozpt36rovr/templateEN-V6-confluence-53.xml.zip?dl=0>



Is there any referring site displaying bad links? How did you find the arc42 links?

hope that helps,
Gernot

PS: We’re currently in the process of streamlining the template - January/February you can expect to find shiny new
versions (v7.0)…


Am 21.12.2015 um 15:45 schrieb awws <notifications@github.com>:

**Comment by gernotstarke** [comment]
the links are working - the confluence is up-and-running.

Reason COULD be firewall/proxy on your side - I mailed you a direct download link (see above too).

**Comment by awws** [comment]
Sorry I wasn't clear - it wasn't confluence that wasn't working - its the link from the landing zone page on confluence to dropbox.
The link on the landing zone page 'for Confluence version 5.x or 6.x' results in a 403.
Thanks for sending me the correct link.

**Comment by gernotstarke** [comment]
need to check that later on.

@awws : just in case you didn't know: you find an EN example of arc42 usage on
https://github.com/aim42/htmlSanityCheck

(its not confluence, but asciidoc... but at least you get an overview of how arc42 can be used on a practical example).

regards, Gernot

**Comment by peterrecore** [comment]
I can confirm.  The link mentioned by @gernotstarke in this thread (https://www.dropbox.com/s/yvlkkozpt36rovr/templateEN-V6-confluence-53.xml.zip?dl=0) worked for me, but the link on the confluence page resulted in a 403, with dropbox suggesting I needed to log in.  (https://dl.dropbox.com/u/45486/arc42-downloads/template-V6/EN/arc42-template-v61-EN.docx

**Comment by gernotstarke** [comment]
sorry for the bad links - I corrected the EN links and added another link to the HTMLSanityCheck example. Currently we have too little EN documentation and samples - I apologize...

**Comment by gernotstarke** [comment]
right u are - the german downloads are still broken.

**Comment by rdmueller** [comment]
sorry, wanted to add some text...
at least, the link from arc42.github.io is still broken... I will try to fix it.

**Comment by rdmueller** [comment]
managed to fix two links - all others on arc42.github.io are still broken...

**Comment by gernotstarke** [comment]
corrected the links.

**Comment by gernotstarke** [comment]
@rdmueller  - could you pls check these links... as I'm the owner of the dropbox, I'm allowed access to all these files...
thx!!

**Comment by rdmueller** [comment]
@gernotstarke all links are ok from my point of view - hope the random part of the link isn't some kind of session :-) 

also updated the remaining links on arc42.github.io
